### ISSUE TITLE
settle recent merge accident

### ISSUE THREAD

**Issue by brianzelip** [NCBI-Hackathons/Librarian_led_Data_Scientist_training#1]
Looks like 3828be7 attempted to add some new work, but inadvertently settled a merge conflict by overwriting recent work with older work.

Here are the files that changed:
- introduction.md
- learning objectves.md
- librarians.md
- outputs.md
- process.md
- social_issue.md

It won't take much to get it sorted out, either by git or by hand.

**Comment by informationista** [comment]
Yes I noticed this the other day and just haven't had a chance to fix it yet.  I'll do so when I have a chance, hopefully later today.
